name: BIST RS Rating Otomatik Analiz

on:
  workflow_dispatch: 
  schedule:
    - cron: '35 15 * * 1-5' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Kontrol
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        run: |
          pip install yfinance pandas

      - name: Analizi Calistir
        run: python script.py

      - name: Sonuclari Kaydet (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: BIST-RS-Rating-Listesi
          path: bist_rs_siralamasi.csv
