name: BIST RS Hesaplayıcı
on:
  schedule:
    - cron: '0 19 * * 1-5' # Hafta içi her akşam 22:00 TSİ (19:00 UTC)
  workflow_dispatch: # İstediğinde manuel çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-level: '3.9'
      - name: Kütüphaneleri Yükle
        run: pip install yfinance pandas numpy
      - name: Hesapla
        run: python script.py
